name: mumo
description: fried chicken.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Design
  flutter_staggered_animations: ^1.0.0
  flutter_native_splash: ^2.3.10
  font_awesome_flutter: ^10.6.0
  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.3.0
  loading_indicator: ^3.1.1
  intl_phone_field: ^3.2.0
  cupertino_icons: ^1.0.2
  country_picker: ^2.0.21
  carousel_slider: ^4.2.1
  quickalert: ^1.0.2
  shimmer: ^3.0.0

  # State management
  flutter_bloc: ^8.1.4

  # Helpers
  shared_preferences: ^2.2.1
  package_info_plus: ^4.2.0
  webview_flutter: ^4.4.2
  url_launcher: ^6.2.2
  image_picker: ^1.0.4
  collection: ^1.15.0
  equatable: ^2.0.5
  sizer: ^2.0.15
  get_it: ^7.6.4
  dartz: ^0.10.1
  intl: ^0.18.1
  uuid: ^4.1.0

  # Network
  internet_connection_checker: ^1.0.0+1
  flutter_facebook_auth: ^5.0.11
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  dio: ^5.3.2

  # Google
  google_maps_webservice: ^0.0.20-nullsafety.5
  flutter_google_places: ^0.3.0
  google_maps_flutter: ^2.5.0
  google_api_headers: ^1.6.0
  firebase_core: ^2.17.0
  google_sign_in: ^6.1.5

  # Location
  geolocator: ^10.1.0

  # Localization
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  background_image: "assets/images/background.jpeg"
  image: "assets/images/logo.png"

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icon.png"
  image_path_ios: "assets/images/icon.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Lateef
      fonts:
        - asset: assets/fonts/Lateef-Light.ttf
          weight: 300
        - asset: assets/fonts/Lateef-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lateef-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lateef-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lateef-Bold.ttf
          weight: 700

    - family: Blocklyn
      fonts:
        - asset: assets/fonts/Blocklyn.ttf
          weight: 300

    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 700
flutter_intl:
  enabled: true
